const Actiontypes = {
  USER_LOGIN: "USER_LOGIN",
  USER_LOGOUT: "USER_LOGOUT",
  SET_NOTIFICATION_COUNTER: "SET_NOTIFICATION_COUNTER",
  SET_USER_TOKEN: "SET_USER_TOKEN",
  STORE_USER_DETAIL: "STORE_USER_DETAIL",
  STORE_USER_FACILITY: "STORE_USER_FACILITY",
};

export default Actiontypes;
